<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nkcadportal"
 *
 * Auto generated by Extension Builder 2018-09-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NK CAD Portal',
	'description' => 'NK CAD Portal',
	'category' => 'plugin',
	'author' => 'Roel Krottje',
	'author_email' => 'roel@netkyngs.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.4.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);